/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const school_Logic = require('./code/school-logic');

class StudentServiceService extends LCAPApplicationService {
    async init() {

        this.before(['CREATE', 'UPDATE'], 'School', async (request) => {
            await school_Logic(request);
        });

        return super.init();
    }
}


module.exports = {
    StudentServiceService
};